on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
