name: Add label on pull request
on:
  pull_request:
    types: [opened]

jobs:
  Add-label-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Add label on pull request
        uses: dealmeidafernando/labeler@v0.14
        with:
          team1: thunderbolts
          membersTeam1: dealmeidafernando; dantunesd; lhkowalski-catho
          labelTeam1: thunderbolts
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
