on:
  push:
    branches-ignore:
      - 'master'

name: Label thunderbolts
jobs:
  fasdfadsf:
    name: Label team
    runs-on: ubuntu-latest
    steps:
    - name: Label team
      uses: pullreminders/label-when-approved-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "thunderbolts"
